[package]
name = "web_crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
yaml-rust = "0.4.5"
anyhow = "1.0.100"
diesel = {version = "2.3.4", features = ["postgres", "chrono"]}
dotenvy = "0.15"