crawler:
  delay: 50
  domain: https://www.geeksforgeeks.org/
  initial_path: dsa/dsa-tutorial-learn-data-structures-and-algorithms/
  mongo: mongodb://root:password@localhost:27017/
  postgres: postgres://user:password@localhost:5432/web_crawler